# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.3"
ports: "80:80;4000:4000;4100:4100"
secrets: open_ai


command:
  build: |
      if [ ! -f node_modules ]; then
          npm update
      fi

  run:


  vite:
      - vite serve

  dev:



  update:
    - "npm update"


  killall:
    - killall jekyll
