version: 1.0

environments:
    coder:
        files:
            - name: "project files"
              enabled: true
              include:
                  - "./**/*"
                  - "./../vite.config.js"
              instructions: |
                  These are all project files. You can edit them as you like.

            - name: "context files"
              enabled: true
              include:
                  - "/opt/.editorconfig"
                  - "/opt/vite.config.js"
              instructions: |
                  These are contextual files that define the environment.
