name: CI/CD Pipeline

on:
    push:
        branches:
            - main
        tags:
            - 'v*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Run tests with Vitest
              run: npm run test

    publish:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@trunkjs'

            - name: Install dependencies
              run: npm ci

            - name: Set package version from tag
              run: |
                  TAG_VERSION="${GITHUB_REF##*/}"
                  echo "Setting version to $TAG_VERSION"
                  npm version $TAG_VERSION --no-git-tag-version

            - name: Build package
              run: npm run build

            - name: Publish to npm
              run: npm publish --access public --tag latest
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
